"""initial_tables

Revision ID: bf1a5ab78157
Revises: 
Create Date: 2026-04-15 11:42:22.641107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1a5ab78157'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_documents_file_hash', table_name='documents')
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.alter_column('evaluations', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('evaluations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='evaluationstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.drop_index('idx_evaluations_collection_id', table_name='evaluations')
    op.create_index(op.f('ix_evaluations_collection_id'), 'evaluations', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_collection_id'), table_name='evaluations')
    op.create_index('idx_evaluations_collection_id', 'evaluations', ['collection_id'], unique=False)
    op.alter_column('evaluations', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='evaluationstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('evaluations', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.create_index('idx_documents_file_hash', 'documents', ['file_hash'], unique=False)
    # ### end Alembic commands ###
